### ISSUE TITLE
What is mailing_lists.project_name good for?

### ISSUE THREAD

**Issue by andygrunwald** [MetricsGrimoire/MailingListStats#47]
I saw the mysql field mailing_lists.project_name.
This field got the default value "NULL" (as string) and not NULL (nothing).
After this i searched for the field in the source code and detected this is not in use.

What is this good for?
Can i remove it? Or does this got a use case?

**Comment by gpoo** [comment]
On second thoughts, it can be useful for adding a meaningful name to a mailing list or a set of mailing lists.

Although, the change must be done manually, it can help to filter the lists to process only a project (say GNOME which has many mailing lists) without altering the schema.

**Comment by andygrunwald** [comment]
Thank you. I thin the manual change is fine as well.
