### ISSUE TITLE
Installation Issue MailingListStat

### ISSUE THREAD

**Issue by MishiR** [MetricsGrimoire/MailingListStats#67]
During installation seems like “install_requires = ['SQLAlchemy >= 0.7'],” from the setup.py is not found.

**Comment by gpoo** [comment]
SQLAlchemy is an external dependency. You have to install it separately. It is usually available in most Linux distributions (assuming you are using Linux).

**Comment by MishiR** [comment]
HI,

Am using Windows 7, do I still need to install it?

/BR

Mehvish Rashid

**Comment by gpoo** [comment]
Yes. The same as the whatever database backend you want to use (Sqlite, MySQL or Postgresql).

**Comment by MishiR** [comment]
Technically SQL Alchemy should install when I run setup.py. when I run:
C:\> C:\Python27\python.exe .\setup.py install

**Comment by MishiR** [comment]
Am wondering if the url is too long for query to process: https://mail-archives.apache.org/mod_mbox/www-repository/200606.mbox/browser

**Comment by gpoo** [comment]
Please, keep the issues separated by topic.

Regarding to the content of your message: 

It seems it is in a format that is not supported by MailingListStat. The tool scraps specific type of html pages, but in the case of Apache, they use JavaScript to render the page.

For example, you can retrieve https://mail-archives.apache.org/mod_mbox/tiles-users/200903.mbox as a file, but if you see the source of https://mail-archives.apache.org/mod_mbox/www-repository/200606.mbox/browser it is:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>www-repository mailing list archives</title>
  <link rel="stylesheet" type="text/css" href="/archives/style.css" />
  <script type="text/javascript" src="/archives/archives.js"></script>
 </head>

 <body id="archives" onload="javascript:loadBrowser ('/mod_mbox/www-repository/200606.mbox');">
  <h1>www-repository mailing list archives</h1>

  <h5>
<a href="http://mail-archives.apache.org/mod_mbox/" title="Back to the archives depot">Site index</a> &middot; <a href="/mod_mbox/www-repository" title="Back to the list index">List index</a></h5> </body>
</html>
```

It should not be hard to write a custom backend for apache archives. These are implemented in https://github.com/MetricsGrimoire/MailingListStats/blob/master/pymlstats/backends.py if you want to give it a try.

**Comment by MishiR** [comment]
Thank you for replying, I am now trying to run the following query on MySQL I think mbox is supported:
mlstats --db-engine=mysql --db-user=ml --db
pache.org/mod_mbox/tiles-users/200903.mbox;

Am still getting an error. Can you please suggest on which URLs MLStats is currently working on?

**Comment by gpoo** [comment]
If you only want to give MLStats a try, anything with Mailman, for example:
http://lists.openstack.org/pipermail/openstack-dev/
https://mail.gnome.org/mailman/listinfo/desktop-devel-list

**Comment by MishiR** [comment]
Thanks, am trying to run this query on MySQL, I am not sure what is wrong now:

mysql>  $ mlstats db-engine=mysql db-user=ml db-password=ml http://lists.openstack.org/pipermail/openstack-dev

**Comment by gpoo** [comment]
What is the output you are getting? Why do you think it is not working?

Please, try to walk in my shoes. I cannott see what you are seeing unless you tell me.
